In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

from IPython.core.display import display, HTML
display(HTML("<style>.output_scroll{height: auto !important;}</style>"))

In [3]:
df=pd.read_excel('Ti6Al4V-NiTi单道沉积试样实验测量熔池形貌数据汇总.xlsx',sheet_name='Sheet1')
df

,试样标号,NiTi粉末材料质量比例,激光功率（W）,移动速度（mm/min）,归一化线质量,激光能量密度（J/mm2）,熔池宽度（μm）,熔池深度（μm）,沉积宽度（μm）,沉积高度（μm）,左润湿角（°）,右润湿角（°）
0,A-1,0.0,600,200,1.000000,90.000000,2803.604,836.036,2075.6760,1762.162,131.315,99.836
1,A-2,0.0,700,200,1.000000,105.000000,3189.189,908.108,2428.8290,1751.351,109.671,91.650
2,A-3,0.0,800,200,1.000000,120.000000,3654.054,1001.802,2900.9010,1888.288,104.036,87.592
3,A-4,0.0,900,200,1.000000,135.000000,4075.676,1095.495,3189.1890,1780.180,92.068,98.973
4,A-5,0.0,600,250,0.600000,72.000000,2661.111,807.477,1824.0740,1659.259,138.094,134.676
5,A-6,0.0,700,250,0.600000,84.000000,3124.074,914.815,2301.8520,1648.148,132.679,112.818
6,A-7,0.0,800,250,0.600000,96.000000,3549.550,936.937,2724.3240,1517.117,99.851,85.486
7,A-8,0.0,900,250,0.600000,108.000000,3960.360,1045.045,3099.0990,1513.514,70.434,87.241
8,A-9,0.0,600,300,0.333333,60.000000,2631.776,798.131,2016.8220,1343.925,85.851,128.480
9,A-10,0.0,700,300,0.333333,70.000000,3018.692,829.907,2366.3550,1338.486,96.607,81.174
10,A-11,0.0,800,300,0.333333,80.000000,3440.741,888.889,2575.9260,1272.222,84.758,74.827
11,A-12,0.0,900,300,0.333333,90.000000,3830.631,1052.252,2980.1800,1269.069,84.346,72.667
12,A-13,0.0,600,350,0.142857,51.428571,2511.111,703.704,1892.5930,1101.852,103.191,93.281
13,A-14,0.0,700,350,0.142857,60.000000,2935.185,827.778,2261.1110,1103.704,84.693,82.924
14,A-15,0.0,800,350,0.142857,68.571429,3331.481,953.704,2711.1110,1107.407,68.371,72.475
15,A-16,0.0,900,350,0.142857,77.142857,3706.542,1044.860,2919.6260,1089.720,74.299,60.186
16,A-17,0.0,600,400,0.000000,45.000000,2476.636,748.598,1908.4110,968.224,90.815,79.312
17,A-18,0.0,700,400,0.000000,52.500000,2798.131,811.215,2128.9720,1061.682,90.000,90.099
18,A-19,0.0,800,400,0.000000,60.000000,3237.383,919.626,2582.2430,1001.869,71.130,64.871
19,A-20,0.0,900,400,0.000000,67.500000,3671.431,1031.776,2906.5421,1033.645,72.460,56.901
20,B-1,0.2,600,200,1.000000,90.000000,3299.065,1101.869,2633.6450,747.664,56.855,37.387
21,B-2,0.2,700,200,1.000000,105.000000,3585.047,1110.280,2885.9810,1323.173,59.699,69.030
22,B-3,0.2,800,200,1.000000,120.000000,3794.595,1149.550,3239.6400,1581.982,65.447,78.397
23,B-4,0.2,900,200,1.000000,135.000000,4198.198,1257.658,3434.2340,1732.710,66.110,78.040
24,B-5,0.2,600,250,0.600000,72.000000,2798.131,739.252,2480.3740,1641.121,72.713,86.786
25,B-6,0.2,700,250,0.600000,84.000000,3141.818,811.818,2745.4550,1813.333,69.777,83.540
26,B-7,0.2,800,250,0.600000,96.000000,3538.182,938.182,3189.0910,1896.364,65.406,74.493
27,B-8,0.2,900,250,0.600000,108.000000,3912.727,1087.273,3447.2730,1770.909,60.771,67.094
28,B-9,0.2,600,300,0.333333,60.000000,2594.595,624.324,2345.9460,1610.811,80.579,79.472
29,B-10,0.2,700,300,0.333333,70.000000,2980.180,762.162,2670.2700,1551.351,75.001,70.521
30,B-11,0.2,800,300,0.333333,80.000000,3357.387,967.863,2758.3200,1537.792,72.208,79.327
31,B-12,0.2,900,300,0.333333,90.000000,3775.846,1111.773,3301.8570,1410.486,54.641,59.071
32,B-13,0.2,600,350,0.142857,51.428571,2607.477,749.533,2254.2060,1158.879,70.253,71.044
33,B-14,0.2,700,350,0.142857,60.000000,2930.841,800.000,2540.1870,1315.888,71.441,71.553
34,B-15,0.2,800,350,0.142857,68.571429,3333.457,932.793,2905.9740,1253.347,57.060,70.746
35,B-16,0.2,900,350,0.142857,77.142857,3758.093,1105.285,3140.7350,1017.693,57.441,54.520
36,B-17,0.2,600,400,0.000000,45.000000,2520.951,666.397,2237.7170,1076.224,71.974,89.059
37,B-18,0.2,700,400,0.000000,52.500000,3025.090,832.849,2627.8940,973.377,57.356,57.812
38,B-19,0.2,800,400,0.000000,60.000000,3327.370,887.273,2869.1740,963.636,71.251,60.386
39,B-20,0.2,900,400,0.000000,67.500000,3778.182,1083.636,3290.9090,830.909,46.985,48.168
40,C-1,0.4,500,200,1.000000,75.000000,2869.813,947.664,2237.3830,770.093,62.137,56.718
41,C-2,0.4,600,200,1.000000,90.000000,3219.319,1038.363,2583.5670,1100.110,63.657,77.291
42,C-3,0.4,700,200,1.000000,105.000000,3519.845,1079.823,2976.8150,1357.092,76.677,69.834
43,C-4,0.4,800,200,1.000000,120.000000,3862.203,1166.712,3265.7970,1589.644,97.991,80.240
44,C-5,0.4,500,250,0.600000,60.000000,2529.630,701.852,2266.6670,1209.259,87.132,83.555
45,C-6,0.4,600,250,0.600000,72.000000,2867.533,828.190,2508.6370,1277.931,93.342,77.739
46,C-7,0.4,700,250,0.600000,84.000000,3237.037,929.630,2818.5190,1364.815,87.007,76.987
47,C-8,0.4,800,250,0.600000,96.000000,3565.326,970.435,3120.1570,1520.000,93.580,87.717
48,C-9,0.4,500,300,0.333333,50.000000,2407.692,622.222,2139.0940,1090.741,113.138,78.918
49,C-10,0.4,600,300,0.333333,60.000000,2824.113,798.148,2488.9720,1009.259,80.194,62.838
50,C-11,0.4,700,300,0.333333,70.000000,3175.669,873.043,2706.0870,1046.957,63.435,58.400
51,C-12,0.4,800,300,0.333333,80.000000,3532.533,1016.819,3021.1810,1135.326,69.847,63.155
52,C-13,0.4,500,350,0.142857,42.857143,2370.406,716.667,1974.1440,729.630,69.522,58.807
53,C-14,0.4,600,350,0.142857,51.428571,2809.224,840.860,2386.6640,798.583,67.561,51.916
54,C-15,0.4,700,350,0.142857,60.000000,3283.333,1033.333,2820.3700,596.296,33.075,34.321
55,C-16,0.4,800,350,0.142857,68.571429,3554.989,1126.978,2970.6380,674.783,37.003,40.605
56,C-17,0.4,500,400,0.000000,37.500000,2423.168,712.307,1993.0710,512.163,42.264,44.042
57,C-18,0.4,600,400,0.000000,45.000000,2883.333,905.556,2450.0000,431.481,34.259,30.038
58,C-19,0.4,700,400,0.000000,52.500000,3316.667,1031.481,2774.0740,462.963,38.870,29.943
59,C-20,0.4,800,400,0.000000,60.000000,3537.391,1172.174,2977.3910,560.000,29.964,30.522
60,D-1,0.6,500,200,1.000000,75.000000,2818.519,970.370,2190.7410,781.481,73.162,63.623
61,D-2,0.6,600,200,1.000000,90.000000,3200.335,997.728,2781.7800,1168.730,79.285,69.295
62,D-3,0.6,700,200,1.000000,105.000000,3481.501,1053.218,2948.0140,1326.170,101.088,80.901
63,D-4,0.6,800,200,1.000000,120.000000,3889.250,1121.005,3323.3840,1519.064,102.808,84.275
64,D-5,0.6,500,250,0.600000,60.000000,2533.388,692.285,2283.4330,1147.276,100.950,72.730
65,D-6,0.6,600,250,0.600000,72.000000,2872.222,805.556,2544.4440,1327.778,115.673,77.241
66,D-7,0.6,700,250,0.600000,84.000000,3242.262,885.189,2939.3170,1444.018,95.283,84.548
67,D-8,0.6,800,250,0.600000,96.000000,3621.709,1012.638,3200.0510,1398.240,86.991,64.629
68,D-9,0.6,500,300,0.333333,50.000000,2427.937,624.074,2176.1810,1103.704,97.996,90.611
69,D-10,0.6,600,300,0.333333,60.000000,2763.003,742.593,2481.5150,1185.185,88.355,72.063
70,D-11,0.6,700,300,0.333333,70.000000,3066.702,820.370,2751.8920,1325.926,78.950,69.459
71,D-12,0.6,800,300,0.333333,80.000000,3472.860,956.074,3118.8500,1301.984,85.550,54.084
72,D-13,0.6,500,350,0.142857,42.857143,2346.296,633.333,2122.2220,987.037,93.466,66.991
73,D-14,0.6,600,350,0.142857,51.428571,2677.110,726.117,2404.7340,1007.788,86.745,59.621
74,D-15,0.6,700,350,0.142857,60.000000,2982.070,818.298,2663.4680,1083.525,81.788,59.685
75,D-16,0.6,800,350,0.142857,68.571429,3258.208,874.197,2939.5630,1236.273,102.483,66.088
76,D-17,0.6,500,400,0.000000,37.500000,2227.778,585.185,2000.0000,935.185,74.453,75.292
77,D-18,0.6,600,400,0.000000,45.000000,2616.084,751.990,2325.5530,830.315,58.419,46.989
78,D-19,0.6,700,400,0.000000,52.500000,2911.196,807.118,2577.8580,991.060,74.313,63.646
79,D-20,0.6,800,400,0.000000,60.000000,3202.752,918.996,2817.5000,909.911,68.817,66.613
80,E-1,0.8,350,200,1.000000,52.500000,2161.314,778.913,1613.2020,522.767,77.931,51.297
81,E-2,0.8,400,200,1.000000,60.000000,2307.800,749.725,1922.4510,888.021,79.108,60.313
82,E-3,0.8,450,200,1.000000,67.500000,2553.296,756.389,2201.8980,1149.533,86.013,82.266
83,E-4,0.8,500,200,1.000000,75.000000,2706.565,755.140,2345.8310,1403.738,97.928,84.451
84,E-5,0.8,350,250,0.600000,42.000000,1951.577,517.811,1631.9570,975.458,108.878,87.060
85,E-6,0.8,400,250,0.600000,48.000000,2168.264,583.178,1895.0510,1102.804,96.571,83.447
86,E-7,0.8,450,250,0.600000,54.000000,2235.767,627.290,1836.0440,1375.400,129.324,101.351
87,E-8,0.8,500,250,0.600000,60.000000,2537.782,660.163,2247.8510,1314.399,96.365,91.783
88,E-9,0.8,350,300,0.333333,35.000000,1824.897,452.188,1527.9610,956.395,101.619,94.772
89,E-10,0.8,400,300,0.333333,40.000000,2094.112,554.219,1800.4700,898.648,86.814,75.272
90,E-11,0.8,450,300,0.333333,45.000000,2306.542,691.589,2001.8690,842.991,76.377,57.911
91,E-12,0.8,500,300,0.333333,50.000000,2493.515,743.925,2209.3960,925.234,69.639,68.658
92,E-13,0.8,350,350,0.142857,30.000000,1882.318,571.963,1557.0500,521.495,46.761,57.728
93,E-14,0.8,400,350,0.142857,34.285714,2069.280,642.991,1708.4480,547.664,56.237,53.922
94,E-15,0.8,450,350,0.142857,38.571429,2224.248,753.888,1755.7210,535.301,60.929,39.997
95,E-16,0.8,500,350,0.142857,42.857143,2474.074,835.185,1935.1850,517.593,56.273,43.112
96,E-17,0.8,350,400,0.000000,26.250000,1838.922,600.000,1454.6480,429.630,63.345,45.841
97,E-18,0.8,400,400,0.000000,30.000000,1996.296,657.407,1591.6670,448.148,49.479,46.948
98,E-19,0.8,450,400,0.000000,33.750000,2225.926,750.000,1792.5930,427.778,48.132,35.710
99,E-20,0.8,500,400,0.000000,37.500000,2333.439,818.519,1848.2230,439.815,45.426,38.117
100,F-1,1.0,350,200,1.000000,52.500000,2018.968,567.133,1674.4060,1045.370,111.101,80.196
101,F-2,1.0,400,200,1.000000,60.000000,2174.013,620.561,1796.3790,1435.514,110.786,106.051
102,F-3,1.0,450,200,1.000000,67.500000,2359.713,712.963,1970.7360,1542.593,133.576,99.908
103,F-4,1.0,500,200,1.000000,75.000000,2479.793,800.000,2158.8300,1531.532,133.196,106.527
104,F-5,1.0,350,250,0.600000,42.000000,1976.121,612.963,1620.5780,625.926,81.753,74.126
105,F-6,1.0,400,250,0.600000,48.000000,2000.104,553.704,1590.7800,1385.185,136.185,105.394
106,F-7,1.0,450,250,0.600000,54.000000,2224.074,650.000,1829.6300,1466.667,125.289,92.851
107,F-8,1.0,500,250,0.600000,60.000000,2334.079,747.826,1979.2800,1467.826,122.403,112.249
108,F-9,1.0,350,300,0.333333,35.000000,1757.525,433.333,1396.3560,1157.407,113.793,92.904
109,F-10,1.0,400,300,0.333333,40.000000,1946.296,474.074,1590.7410,1261.111,115.096,104.948
110,F-11,1.0,450,300,0.333333,45.000000,2026.200,607.407,1729.8530,1287.037,113.427,104.390
111,F-12,1.0,500,300,0.333333,50.000000,2227.951,698.148,1942.6240,1235.185,95.057,104.985
112,F-13,1.0,350,350,0.142857,30.000000,1711.737,424.074,1424.4220,1042.593,87.098,115.757
113,F-14,1.0,400,350,0.142857,34.285714,1866.667,505.556,1618.5190,1096.296,87.207,81.876
114,F-15,1.0,450,350,0.142857,38.571429,2050.030,618.519,1731.5300,1074.074,85.389,85.985
115,F-16,1.0,500,350,0.142857,42.857143,2253.704,692.593,1950.0000,1012.963,89.597,75.340
116,F-17,1.0,350,400,0.000000,26.250000,1672.222,418.519,1388.5800,844.444,89.102,82.042
117,F-18,1.0,400,400,0.000000,30.000000,1814.929,496.296,1531.5530,946.296,103.125,77.249
118,F-19,1.0,450,400,0.000000,33.750000,2014.815,551.852,1759.2590,862.963,84.129,75.736
119,F-20,1.0,500,400,0.000000,37.500000,2225.975,640.741,1968.5610,850.000,86.712,67.957

## Predict Molten Pool Width

In [4]:
df_width = df.drop(df.columns[[0, 7, 8, 9, 10, 11]], axis=1)
df_width

     NiTi粉末材料质量比例  激光功率（W）  移动速度（mm/min）    归一化线质量  激光能量密度（J/mm2）  熔池宽度（μm）
0             0.0      600           200  1.000000      90.000000  2803.604
1             0.0      700           200  1.000000     105.000000  3189.189
2             0.0      800           200  1.000000     120.000000  3654.054
3             0.0      900           200  1.000000     135.000000  4075.676
4             0.0      600           250  0.600000      72.000000  2661.111
5             0.0      700           250  0.600000      84.000000  3124.074
6             0.0      800           250  0.600000      96.000000  3549.550
7             0.0      900           250  0.600000     108.000000  3960.360
8             0.0      600           300  0.333333      60.000000  2631.776
9             0.0      700           300  0.333333      70.000000  3018.692
10            0.0      800           300  0.333333      80.000000  3440.741
11            0.0      900           300  0.333333      90.000000  3830.631
12            0.0      600           350  0.142857      51.428571  2511.111
13            0.0      700           350  0.142857      60.000000  2935.185
14            0.0      800           350  0.142857      68.571429  3331.481
15            0.0      900           350  0.142857      77.142857  3706.542
16            0.0      600           400  0.000000      45.000000  2476.636
17            0.0      700           400  0.000000      52.500000  2798.131
18            0.0      800           400  0.000000      60.000000  3237.383
19            0.0      900           400  0.000000      67.500000  3671.431
20            0.2      600           200  1.000000      90.000000  3299.065
21            0.2      700           200  1.000000     105.000000  3585.047
22            0.2      800           200  1.000000     120.000000  3794.595
23            0.2      900           200  1.000000     135.000000  4198.198
24            0.2      600           250  0.600000      72.000000  2798.131
25            0.2      700           250  0.600000      84.000000  3141.818
26            0.2      800           250  0.600000      96.000000  3538.182
27            0.2      900           250  0.600000     108.000000  3912.727
28            0.2      600           300  0.333333      60.000000  2594.595
29            0.2      700           300  0.333333      70.000000  2980.180
30            0.2      800           300  0.333333      80.000000  3357.387
31            0.2      900           300  0.333333      90.000000  3775.846
32            0.2      600           350  0.142857      51.428571  2607.477
33            0.2      700           350  0.142857      60.000000  2930.841
34            0.2      800           350  0.142857      68.571429  3333.457
35            0.2      900           350  0.142857      77.142857  3758.093
36            0.2      600           400  0.000000      45.000000  2520.951
37            0.2      700           400  0.000000      52.500000  3025.090
38            0.2      800           400  0.000000      60.000000  3327.370
39            0.2      900           400  0.000000      67.500000  3778.182
40            0.4      500           200  1.000000      75.000000  2869.813
41            0.4      600           200  1.000000      90.000000  3219.319
42            0.4      700           200  1.000000     105.000000  3519.845
43            0.4      800           200  1.000000     120.000000  3862.203
44            0.4      500           250  0.600000      60.000000  2529.630
45            0.4      600           250  0.600000      72.000000  2867.533
46            0.4      700           250  0.600000      84.000000  3237.037
47            0.4      800           250  0.600000      96.000000  3565.326
48            0.4      500           300  0.333333      50.000000  2407.692
49            0.4      600           300  0.333333      60.000000  2824.113
50            0.4      700           300  0.333333      70.000000  3175.669
51            0.4      800           300  0.333333      80.000000  3532.533
52            0.4      500           350  0.142857      42.857143  2370.406
53            0.4      600           350  0.142857      51.428571  2809.224
54            0.4      700           350  0.142857      60.000000  3283.333
55            0.4      800           350  0.142857      68.571429  3554.989
56            0.4      500           400  0.000000      37.500000  2423.168
57            0.4      600           400  0.000000      45.000000  2883.333
58            0.4      700           400  0.000000      52.500000  3316.667
59            0.4      800           400  0.000000      60.000000  3537.391
60            0.6      500           200  1.000000      75.000000  2818.519
61            0.6      600           200  1.000000      90.000000  3200.335
62            0.6      700           200  1.000000     105.000000  3481.501
63            0.6      800           200  1.000000     120.000000  3889.250
64            0.6      500           250  0.600000      60.000000  2533.388
65            0.6      600           250  0.600000      72.000000  2872.222
66            0.6      700           250  0.600000      84.000000  3242.262
67            0.6      800           250  0.600000      96.000000  3621.709
68            0.6      500           300  0.333333      50.000000  2427.937
69            0.6      600           300  0.333333      60.000000  2763.003
70            0.6      700           300  0.333333      70.000000  3066.702
71            0.6      800           300  0.333333      80.000000  3472.860
72            0.6      500           350  0.142857      42.857143  2346.296
73            0.6      600           350  0.142857      51.428571  2677.110
74            0.6      700           350  0.142857      60.000000  2982.070
75            0.6      800           350  0.142857      68.571429  3258.208
76            0.6      500           400  0.000000      37.500000  2227.778
77            0.6      600           400  0.000000      45.000000  2616.084
78            0.6      700           400  0.000000      52.500000  2911.196
79            0.6      800           400  0.000000      60.000000  3202.752
80            0.8      350           200  1.000000      52.500000  2161.314
81            0.8      400           200  1.000000      60.000000  2307.800
82            0.8      450           200  1.000000      67.500000  2553.296
83            0.8      500           200  1.000000      75.000000  2706.565
84            0.8      350           250  0.600000      42.000000  1951.577
85            0.8      400           250  0.600000      48.000000  2168.264
86            0.8      450           250  0.600000      54.000000  2235.767
87            0.8      500           250  0.600000      60.000000  2537.782
88            0.8      350           300  0.333333      35.000000  1824.897
89            0.8      400           300  0.333333      40.000000  2094.112
90            0.8      450           300  0.333333      45.000000  2306.542
91            0.8      500           300  0.333333      50.000000  2493.515
92            0.8      350           350  0.142857      30.000000  1882.318
93            0.8      400           350  0.142857      34.285714  2069.280
94            0.8      450           350  0.142857      38.571429  2224.248
95            0.8      500           350  0.142857      42.857143  2474.074
96            0.8      350           400  0.000000      26.250000  1838.922
97            0.8      400           400  0.000000      30.000000  1996.296
98            0.8      450           400  0.000000      33.750000  2225.926
99            0.8      500           400  0.000000      37.500000  2333.439
100           1.0      350           200  1.000000      52.500000  2018.968
101           1.0      400           200  1.000000      60.000000  2174.013
102           1.0      450           200  1.000000      67.500000  2359.713
103           1.0      500           200  1.000000      75.000000  2479.793
104           1.0      350           250  0.600000      42.000000  1976.121
105           1.0      400           250  0.600000      48.000000  2000.104
106           1.0      450           250  0.600000      54.000000  2224.074
107           1.0      500           250  0.600000      60.000000  2334.079
108           1.0      350           300  0.333333      35.000000  1757.525
109           1.0      400           300  0.333333      40.000000  1946.296
110           1.0      450           300  0.333333      45.000000  2026.200
111           1.0      500           300  0.333333      50.000000  2227.951
112           1.0      350           350  0.142857      30.000000  1711.737
113           1.0      400           350  0.142857      34.285714  1866.667
114           1.0      450           350  0.142857      38.571429  2050.030
115           1.0      500           350  0.142857      42.857143  2253.704
116           1.0      350           400  0.000000      26.250000  1672.222
117           1.0      400           400  0.000000      30.000000  1814.929
118           1.0      450           400  0.000000      33.750000  2014.815
119           1.0      500           400  0.000000      37.500000  2225.975

In [5]:
df_width.describe()

,NiTi粉末材料质量比例,激光功率（W）,移动速度（mm/min）,归一化线质量,激光能量密度（J/mm2）,熔池宽度（μm）
count,120.000000,120.000000,120.00000,120.000000,120.000000,120.000000
mean,0.500000,608.333333,300.00000,0.415238,64.570238,2814.882050
std,0.342997,167.574558,71.00716,0.356285,24.505039,633.983643
min,0.000000,350.000000,200.00000,0.000000,26.250000,1672.222000
25%,0.200000,487.500000,250.00000,0.142857,45.000000,2293.332500
50%,0.500000,600.000000,300.00000,0.333333,60.000000,2800.867500
75%,0.800000,725.000000,350.00000,0.600000,77.857143,3319.342750
max,1.000000,900.000000,400.00000,1.000000,135.000000,4198.198000

In [6]:
X = df_width.iloc[:, :-1]
y = df_width.iloc[:, -1]

In [7]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from tabpfn import TabPFNRegressor

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

regressor = TabPFNRegressor()  
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f'TabPFN模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN模型在测试集上的R²得分:', r2)

TabPFN模型在测试集上的均方根误差: 60.4359
TabPFN模型在测试集上的R²得分: 0.9894767984207724

In [9]:
from tabpfn_extensions.post_hoc_ensembles.sklearn_interface import AutoTabPFNRegressor

reg = AutoTabPFNRegressor(max_time=300, device="cuda") 
reg.fit(X_train, y_train)

predictions = reg.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)

print(f'TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN_Post Hoc Ensembling模型在测试集上的R²得分:', r2)

INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Order of selections: [np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(4), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(15)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Val loss over iterations: [np.float64(1760.2568372879714), np.float64(1760.2568372879714), np.float64(1760.2568372879714), np.float64(1760.2568372879714), np.float64(1760.2568372879714), np.float64(1760.2568372879714), np.float64(1760.2568372879714), np.float64(1760.2568372879714), np.float64(1760.2568372879714), np.float64(1759.7607936731954), np.float64(1759.2978661459529), np.float64(1758.98970774012), np.float64(1758.784069231196), np.float64(1758.6480161231657), np.float64(1758.5601257545995), np.float64(1758.5060902500252), np.float64(1758.4761369820146), np.float64(1758.463462179554), np.float64(1758.4632509117023), np.float64(1758.4632509117023), np.float64(1758.4632509117023), np.float64(1758.4632509117023), np.float64(1758.4632509117023), np.float64(1758.4632509117023), np.float64(1758.4632509117023)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Model losses: [1760.25683729 1956.88337919 1991.36527839 2040.29070072 2308.53279616
 2337.45427536 2387.43266876 2572.45732519 2703.83768016 2768.80058353
 2809.90902803 2961.62028449 2963.66659177 2974.69463617 2999.85354991
 3028.85717067 3080.01995934 3145.37943496 3173.10433478 3256.13952185
 3293.64078367 4471.46382798 4941.57747716 5154.7066077  8728.48589229]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Best weights: [0.94736842 0.         0.         0.         0.05263158 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.        ]

TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: 51.9656
TabPFN_Post Hoc Ensembling模型在测试集上的R²得分: 0.9922198046906245

## Predict Molten Pool Depth

In [10]:
df_depth = df.drop(df.columns[[0, 6, 8, 9, 10, 11]], axis=1)
df_depth

     NiTi粉末材料质量比例  激光功率（W）  移动速度（mm/min）    归一化线质量  激光能量密度（J/mm2）  熔池深度（μm）
0             0.0      600           200  1.000000      90.000000   836.036
1             0.0      700           200  1.000000     105.000000   908.108
2             0.0      800           200  1.000000     120.000000  1001.802
3             0.0      900           200  1.000000     135.000000  1095.495
4             0.0      600           250  0.600000      72.000000   807.477
5             0.0      700           250  0.600000      84.000000   914.815
6             0.0      800           250  0.600000      96.000000   936.937
7             0.0      900           250  0.600000     108.000000  1045.045
8             0.0      600           300  0.333333      60.000000   798.131
9             0.0      700           300  0.333333      70.000000   829.907
10            0.0      800           300  0.333333      80.000000   888.889
11            0.0      900           300  0.333333      90.000000  1052.252
12            0.0      600           350  0.142857      51.428571   703.704
13            0.0      700           350  0.142857      60.000000   827.778
14            0.0      800           350  0.142857      68.571429   953.704
15            0.0      900           350  0.142857      77.142857  1044.860
16            0.0      600           400  0.000000      45.000000   748.598
17            0.0      700           400  0.000000      52.500000   811.215
18            0.0      800           400  0.000000      60.000000   919.626
19            0.0      900           400  0.000000      67.500000  1031.776
20            0.2      600           200  1.000000      90.000000  1101.869
21            0.2      700           200  1.000000     105.000000  1110.280
22            0.2      800           200  1.000000     120.000000  1149.550
23            0.2      900           200  1.000000     135.000000  1257.658
24            0.2      600           250  0.600000      72.000000   739.252
25            0.2      700           250  0.600000      84.000000   811.818
26            0.2      800           250  0.600000      96.000000   938.182
27            0.2      900           250  0.600000     108.000000  1087.273
28            0.2      600           300  0.333333      60.000000   624.324
29            0.2      700           300  0.333333      70.000000   762.162
30            0.2      800           300  0.333333      80.000000   967.863
31            0.2      900           300  0.333333      90.000000  1111.773
32            0.2      600           350  0.142857      51.428571   749.533
33            0.2      700           350  0.142857      60.000000   800.000
34            0.2      800           350  0.142857      68.571429   932.793
35            0.2      900           350  0.142857      77.142857  1105.285
36            0.2      600           400  0.000000      45.000000   666.397
37            0.2      700           400  0.000000      52.500000   832.849
38            0.2      800           400  0.000000      60.000000   887.273
39            0.2      900           400  0.000000      67.500000  1083.636
40            0.4      500           200  1.000000      75.000000   947.664
41            0.4      600           200  1.000000      90.000000  1038.363
42            0.4      700           200  1.000000     105.000000  1079.823
43            0.4      800           200  1.000000     120.000000  1166.712
44            0.4      500           250  0.600000      60.000000   701.852
45            0.4      600           250  0.600000      72.000000   828.190
46            0.4      700           250  0.600000      84.000000   929.630
47            0.4      800           250  0.600000      96.000000   970.435
48            0.4      500           300  0.333333      50.000000   622.222
49            0.4      600           300  0.333333      60.000000   798.148
50            0.4      700           300  0.333333      70.000000   873.043
51            0.4      800           300  0.333333      80.000000  1016.819
52            0.4      500           350  0.142857      42.857143   716.667
53            0.4      600           350  0.142857      51.428571   840.860
54            0.4      700           350  0.142857      60.000000  1033.333
55            0.4      800           350  0.142857      68.571429  1126.978
56            0.4      500           400  0.000000      37.500000   712.307
57            0.4      600           400  0.000000      45.000000   905.556
58            0.4      700           400  0.000000      52.500000  1031.481
59            0.4      800           400  0.000000      60.000000  1172.174
60            0.6      500           200  1.000000      75.000000   970.370
61            0.6      600           200  1.000000      90.000000   997.728
62            0.6      700           200  1.000000     105.000000  1053.218
63            0.6      800           200  1.000000     120.000000  1121.005
64            0.6      500           250  0.600000      60.000000   692.285
65            0.6      600           250  0.600000      72.000000   805.556
66            0.6      700           250  0.600000      84.000000   885.189
67            0.6      800           250  0.600000      96.000000  1012.638
68            0.6      500           300  0.333333      50.000000   624.074
69            0.6      600           300  0.333333      60.000000   742.593
70            0.6      700           300  0.333333      70.000000   820.370
71            0.6      800           300  0.333333      80.000000   956.074
72            0.6      500           350  0.142857      42.857143   633.333
73            0.6      600           350  0.142857      51.428571   726.117
74            0.6      700           350  0.142857      60.000000   818.298
75            0.6      800           350  0.142857      68.571429   874.197
76            0.6      500           400  0.000000      37.500000   585.185
77            0.6      600           400  0.000000      45.000000   751.990
78            0.6      700           400  0.000000      52.500000   807.118
79            0.6      800           400  0.000000      60.000000   918.996
80            0.8      350           200  1.000000      52.500000   778.913
81            0.8      400           200  1.000000      60.000000   749.725
82            0.8      450           200  1.000000      67.500000   756.389
83            0.8      500           200  1.000000      75.000000   755.140
84            0.8      350           250  0.600000      42.000000   517.811
85            0.8      400           250  0.600000      48.000000   583.178
86            0.8      450           250  0.600000      54.000000   627.290
87            0.8      500           250  0.600000      60.000000   660.163
88            0.8      350           300  0.333333      35.000000   452.188
89            0.8      400           300  0.333333      40.000000   554.219
90            0.8      450           300  0.333333      45.000000   691.589
91            0.8      500           300  0.333333      50.000000   743.925
92            0.8      350           350  0.142857      30.000000   571.963
93            0.8      400           350  0.142857      34.285714   642.991
94            0.8      450           350  0.142857      38.571429   753.888
95            0.8      500           350  0.142857      42.857143   835.185
96            0.8      350           400  0.000000      26.250000   600.000
97            0.8      400           400  0.000000      30.000000   657.407
98            0.8      450           400  0.000000      33.750000   750.000
99            0.8      500           400  0.000000      37.500000   818.519
100           1.0      350           200  1.000000      52.500000   567.133
101           1.0      400           200  1.000000      60.000000   620.561
102           1.0      450           200  1.000000      67.500000   712.963
103           1.0      500           200  1.000000      75.000000   800.000
104           1.0      350           250  0.600000      42.000000   612.963
105           1.0      400           250  0.600000      48.000000   553.704
106           1.0      450           250  0.600000      54.000000   650.000
107           1.0      500           250  0.600000      60.000000   747.826
108           1.0      350           300  0.333333      35.000000   433.333
109           1.0      400           300  0.333333      40.000000   474.074
110           1.0      450           300  0.333333      45.000000   607.407
111           1.0      500           300  0.333333      50.000000   698.148
112           1.0      350           350  0.142857      30.000000   424.074
113           1.0      400           350  0.142857      34.285714   505.556
114           1.0      450           350  0.142857      38.571429   618.519
115           1.0      500           350  0.142857      42.857143   692.593
116           1.0      350           400  0.000000      26.250000   418.519
117           1.0      400           400  0.000000      30.000000   496.296
118           1.0      450           400  0.000000      33.750000   551.852
119           1.0      500           400  0.000000      37.500000   640.741

In [11]:
df_depth.describe()

,NiTi粉末材料质量比例,激光功率（W）,移动速度（mm/min）,归一化线质量,激光能量密度（J/mm2）,熔池深度（μm）
count,120.000000,120.000000,120.00000,120.000000,120.000000,120.000000
mean,0.500000,608.333333,300.00000,0.415238,64.570238,812.593842
std,0.342997,167.574558,71.00716,0.356285,24.505039,191.163796
min,0.000000,350.000000,200.00000,0.000000,26.250000,418.519000
25%,0.200000,487.500000,250.00000,0.142857,45.000000,664.838500
50%,0.500000,600.000000,300.00000,0.333333,60.000000,806.337000
75%,0.800000,725.000000,350.00000,0.600000,77.857143,954.296500
max,1.000000,900.000000,400.00000,1.000000,135.000000,1257.658000

In [12]:
X = df_depth.iloc[:, :-1]
y = df_depth.iloc[:, -1]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

regressor = TabPFNRegressor()  
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f'TabPFN模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN模型在测试集上的R²得分:', r2)

TabPFN模型在测试集上的均方根误差: 50.9300
TabPFN模型在测试集上的R²得分: 0.8948190105106684

In [14]:
reg = AutoTabPFNRegressor(max_time=300, device="cuda") 
reg.fit(X_train, y_train)

predictions = reg.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)

print(f'TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN_Post Hoc Ensembling模型在测试集上的R²得分:', r2)

INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Order of selections: [np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(7), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Val loss over iterations: [np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.5124397667787), np.float64(2231.299477189367), np.float64(2231.0458770787395), np.float64(2230.85535951504), np.float64(2230.711579960267), np.float64(2230.6029199404884), np.float64(2230.520970616212), np.float64(2230.4595490093034), np.float64(2230.41404465878), np.float64(2230.3809765802853), np.float64(2230.3576871733944), np.float64(2230.3421271599454), np.float64(2230.332702164904)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Model losses: [2231.51243977 2394.66883994 2447.86375075 2452.55679982 2756.97290573
 2946.99474789 2995.99859194 3011.83898987 3272.29972997 3308.05813016
 3316.0182248  3466.22619237 3474.17138577 3827.34703056 3878.84598224
 4057.8318107  4075.10695511 4155.31347525 4166.95528203 4253.75392085
 4402.38061292 4496.87136479 5020.6912549  5822.80821682 6136.67181455]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Best weights: [0.96 0.   0.   0.   0.   0.   0.   0.04 0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]

TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: 52.7243
TabPFN_Post Hoc Ensembling模型在测试集上的R²得分: 0.8872771496946492

## Predict Deposited Width

In [15]:
df_deposited_width = df.drop(df.columns[[0, 6, 7, 9, 10, 11]], axis=1)
df_deposited_width

     NiTi粉末材料质量比例  激光功率（W）  移动速度（mm/min）    归一化线质量  激光能量密度（J/mm2）   沉积宽度（μm）
0             0.0      600           200  1.000000      90.000000  2075.6760
1             0.0      700           200  1.000000     105.000000  2428.8290
2             0.0      800           200  1.000000     120.000000  2900.9010
3             0.0      900           200  1.000000     135.000000  3189.1890
4             0.0      600           250  0.600000      72.000000  1824.0740
5             0.0      700           250  0.600000      84.000000  2301.8520
6             0.0      800           250  0.600000      96.000000  2724.3240
7             0.0      900           250  0.600000     108.000000  3099.0990
8             0.0      600           300  0.333333      60.000000  2016.8220
9             0.0      700           300  0.333333      70.000000  2366.3550
10            0.0      800           300  0.333333      80.000000  2575.9260
11            0.0      900           300  0.333333      90.000000  2980.1800
12            0.0      600           350  0.142857      51.428571  1892.5930
13            0.0      700           350  0.142857      60.000000  2261.1110
14            0.0      800           350  0.142857      68.571429  2711.1110
15            0.0      900           350  0.142857      77.142857  2919.6260
16            0.0      600           400  0.000000      45.000000  1908.4110
17            0.0      700           400  0.000000      52.500000  2128.9720
18            0.0      800           400  0.000000      60.000000  2582.2430
19            0.0      900           400  0.000000      67.500000  2906.5421
20            0.2      600           200  1.000000      90.000000  2633.6450
21            0.2      700           200  1.000000     105.000000  2885.9810
22            0.2      800           200  1.000000     120.000000  3239.6400
23            0.2      900           200  1.000000     135.000000  3434.2340
24            0.2      600           250  0.600000      72.000000  2480.3740
25            0.2      700           250  0.600000      84.000000  2745.4550
26            0.2      800           250  0.600000      96.000000  3189.0910
27            0.2      900           250  0.600000     108.000000  3447.2730
28            0.2      600           300  0.333333      60.000000  2345.9460
29            0.2      700           300  0.333333      70.000000  2670.2700
30            0.2      800           300  0.333333      80.000000  2758.3200
31            0.2      900           300  0.333333      90.000000  3301.8570
32            0.2      600           350  0.142857      51.428571  2254.2060
33            0.2      700           350  0.142857      60.000000  2540.1870
34            0.2      800           350  0.142857      68.571429  2905.9740
35            0.2      900           350  0.142857      77.142857  3140.7350
36            0.2      600           400  0.000000      45.000000  2237.7170
37            0.2      700           400  0.000000      52.500000  2627.8940
38            0.2      800           400  0.000000      60.000000  2869.1740
39            0.2      900           400  0.000000      67.500000  3290.9090
40            0.4      500           200  1.000000      75.000000  2237.3830
41            0.4      600           200  1.000000      90.000000  2583.5670
42            0.4      700           200  1.000000     105.000000  2976.8150
43            0.4      800           200  1.000000     120.000000  3265.7970
44            0.4      500           250  0.600000      60.000000  2266.6670
45            0.4      600           250  0.600000      72.000000  2508.6370
46            0.4      700           250  0.600000      84.000000  2818.5190
47            0.4      800           250  0.600000      96.000000  3120.1570
48            0.4      500           300  0.333333      50.000000  2139.0940
49            0.4      600           300  0.333333      60.000000  2488.9720
50            0.4      700           300  0.333333      70.000000  2706.0870
51            0.4      800           300  0.333333      80.000000  3021.1810
52            0.4      500           350  0.142857      42.857143  1974.1440
53            0.4      600           350  0.142857      51.428571  2386.6640
54            0.4      700           350  0.142857      60.000000  2820.3700
55            0.4      800           350  0.142857      68.571429  2970.6380
56            0.4      500           400  0.000000      37.500000  1993.0710
57            0.4      600           400  0.000000      45.000000  2450.0000
58            0.4      700           400  0.000000      52.500000  2774.0740
59            0.4      800           400  0.000000      60.000000  2977.3910
60            0.6      500           200  1.000000      75.000000  2190.7410
61            0.6      600           200  1.000000      90.000000  2781.7800
62            0.6      700           200  1.000000     105.000000  2948.0140
63            0.6      800           200  1.000000     120.000000  3323.3840
64            0.6      500           250  0.600000      60.000000  2283.4330
65            0.6      600           250  0.600000      72.000000  2544.4440
66            0.6      700           250  0.600000      84.000000  2939.3170
67            0.6      800           250  0.600000      96.000000  3200.0510
68            0.6      500           300  0.333333      50.000000  2176.1810
69            0.6      600           300  0.333333      60.000000  2481.5150
70            0.6      700           300  0.333333      70.000000  2751.8920
71            0.6      800           300  0.333333      80.000000  3118.8500
72            0.6      500           350  0.142857      42.857143  2122.2220
73            0.6      600           350  0.142857      51.428571  2404.7340
74            0.6      700           350  0.142857      60.000000  2663.4680
75            0.6      800           350  0.142857      68.571429  2939.5630
76            0.6      500           400  0.000000      37.500000  2000.0000
77            0.6      600           400  0.000000      45.000000  2325.5530
78            0.6      700           400  0.000000      52.500000  2577.8580
79            0.6      800           400  0.000000      60.000000  2817.5000
80            0.8      350           200  1.000000      52.500000  1613.2020
81            0.8      400           200  1.000000      60.000000  1922.4510
82            0.8      450           200  1.000000      67.500000  2201.8980
83            0.8      500           200  1.000000      75.000000  2345.8310
84            0.8      350           250  0.600000      42.000000  1631.9570
85            0.8      400           250  0.600000      48.000000  1895.0510
86            0.8      450           250  0.600000      54.000000  1836.0440
87            0.8      500           250  0.600000      60.000000  2247.8510
88            0.8      350           300  0.333333      35.000000  1527.9610
89            0.8      400           300  0.333333      40.000000  1800.4700
90            0.8      450           300  0.333333      45.000000  2001.8690
91            0.8      500           300  0.333333      50.000000  2209.3960
92            0.8      350           350  0.142857      30.000000  1557.0500
93            0.8      400           350  0.142857      34.285714  1708.4480
94            0.8      450           350  0.142857      38.571429  1755.7210
95            0.8      500           350  0.142857      42.857143  1935.1850
96            0.8      350           400  0.000000      26.250000  1454.6480
97            0.8      400           400  0.000000      30.000000  1591.6670
98            0.8      450           400  0.000000      33.750000  1792.5930
99            0.8      500           400  0.000000      37.500000  1848.2230
100           1.0      350           200  1.000000      52.500000  1674.4060
101           1.0      400           200  1.000000      60.000000  1796.3790
102           1.0      450           200  1.000000      67.500000  1970.7360
103           1.0      500           200  1.000000      75.000000  2158.8300
104           1.0      350           250  0.600000      42.000000  1620.5780
105           1.0      400           250  0.600000      48.000000  1590.7800
106           1.0      450           250  0.600000      54.000000  1829.6300
107           1.0      500           250  0.600000      60.000000  1979.2800
108           1.0      350           300  0.333333      35.000000  1396.3560
109           1.0      400           300  0.333333      40.000000  1590.7410
110           1.0      450           300  0.333333      45.000000  1729.8530
111           1.0      500           300  0.333333      50.000000  1942.6240
112           1.0      350           350  0.142857      30.000000  1424.4220
113           1.0      400           350  0.142857      34.285714  1618.5190
114           1.0      450           350  0.142857      38.571429  1731.5300
115           1.0      500           350  0.142857      42.857143  1950.0000
116           1.0      350           400  0.000000      26.250000  1388.5800
117           1.0      400           400  0.000000      30.000000  1531.5530
118           1.0      450           400  0.000000      33.750000  1759.2590
119           1.0      500           400  0.000000      37.500000  1968.5610

In [16]:
df_deposited_width.describe()

,NiTi粉末材料质量比例,激光功率（W）,移动速度（mm/min）,归一化线质量,激光能量密度（J/mm2）,沉积宽度（μm）
count,120.000000,120.000000,120.00000,120.000000,120.000000,120.000000
mean,0.500000,608.333333,300.00000,0.415238,64.570238,2361.604826
std,0.342997,167.574558,71.00716,0.356285,24.505039,543.593936
min,0.000000,350.000000,200.00000,0.000000,26.250000,1388.580000
25%,0.200000,487.500000,250.00000,0.142857,45.000000,1918.941000
50%,0.500000,600.000000,300.00000,0.333333,60.000000,2335.692000
75%,0.800000,725.000000,350.00000,0.600000,77.857143,2817.754750
max,1.000000,900.000000,400.00000,1.000000,135.000000,3447.273000

In [17]:
X = df_deposited_width.iloc[:, :-1]
y = df_deposited_width.iloc[:, -1]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

regressor = TabPFNRegressor()  
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f'TabPFN模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN模型在测试集上的R²得分:', r2)

TabPFN模型在测试集上的均方根误差: 81.3803
TabPFN模型在测试集上的R²得分: 0.9736208011456411

In [19]:
reg = AutoTabPFNRegressor(max_time=300, device="cuda") 
reg.fit(X_train, y_train)

predictions = reg.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)

print(f'TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN_Post Hoc Ensembling模型在测试集上的R²得分:', r2)

INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Order of selections: [np.int64(0), np.int64(4), np.int64(0), np.int64(18), np.int64(0), np.int64(4), np.int64(0), np.int64(4), np.int64(0), np.int64(18), np.int64(0), np.int64(4), np.int64(0), np.int64(4), np.int64(0), np.int64(0), np.int64(18), np.int64(0), np.int64(4), np.int64(0), np.int64(4), np.int64(0), np.int64(18), np.int64(0), np.int64(4)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Val loss over iterations: [np.float64(6248.270013414831), np.float64(5243.940754766223), np.float64(5243.940754766223), np.float64(5212.474199984879), np.float64(5212.474199984879), np.float64(5199.877567973351), np.float64(5199.877567973351), np.float64(5199.877567973351), np.float64(5199.877567973351), np.float64(5199.877567973351), np.float64(5196.055467212743), np.float64(5196.055467212743), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718), np.float64(5194.839219655718)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Model losses: [ 6248.27001341  6509.70944622  6525.64415951  6575.01018102
  6586.68995703  6713.12405291  6868.80469305  6884.83463514
  6918.1314535   6941.93627413  6953.31741344  7077.22018461
  7162.4987157   7170.33338616  7372.30337066  7438.63126469
  7452.96891188  7614.32809749  7629.46999479  7657.57125888
  7664.22798114  8349.33271975  8753.04504456  9490.48048759
 10030.11365713]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Best weights: [0.53846154 0.         0.         0.         0.30769231 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.15384615 0.         0.         0.         0.         0.
 0.        ]

TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: 87.8026
TabPFN_Post Hoc Ensembling模型在测试集上的R²得分: 0.9692929222377004

## Predict Deposited Height

In [20]:
df_deposited_height = df.drop(df.columns[[0, 6, 7, 8, 10, 11]], axis=1)
df_deposited_height

     NiTi粉末材料质量比例  激光功率（W）  移动速度（mm/min）    归一化线质量  激光能量密度（J/mm2）  沉积高度（μm）
0             0.0      600           200  1.000000      90.000000  1762.162
1             0.0      700           200  1.000000     105.000000  1751.351
2             0.0      800           200  1.000000     120.000000  1888.288
3             0.0      900           200  1.000000     135.000000  1780.180
4             0.0      600           250  0.600000      72.000000  1659.259
5             0.0      700           250  0.600000      84.000000  1648.148
6             0.0      800           250  0.600000      96.000000  1517.117
7             0.0      900           250  0.600000     108.000000  1513.514
8             0.0      600           300  0.333333      60.000000  1343.925
9             0.0      700           300  0.333333      70.000000  1338.486
10            0.0      800           300  0.333333      80.000000  1272.222
11            0.0      900           300  0.333333      90.000000  1269.069
12            0.0      600           350  0.142857      51.428571  1101.852
13            0.0      700           350  0.142857      60.000000  1103.704
14            0.0      800           350  0.142857      68.571429  1107.407
15            0.0      900           350  0.142857      77.142857  1089.720
16            0.0      600           400  0.000000      45.000000   968.224
17            0.0      700           400  0.000000      52.500000  1061.682
18            0.0      800           400  0.000000      60.000000  1001.869
19            0.0      900           400  0.000000      67.500000  1033.645
20            0.2      600           200  1.000000      90.000000   747.664
21            0.2      700           200  1.000000     105.000000  1323.173
22            0.2      800           200  1.000000     120.000000  1581.982
23            0.2      900           200  1.000000     135.000000  1732.710
24            0.2      600           250  0.600000      72.000000  1641.121
25            0.2      700           250  0.600000      84.000000  1813.333
26            0.2      800           250  0.600000      96.000000  1896.364
27            0.2      900           250  0.600000     108.000000  1770.909
28            0.2      600           300  0.333333      60.000000  1610.811
29            0.2      700           300  0.333333      70.000000  1551.351
30            0.2      800           300  0.333333      80.000000  1537.792
31            0.2      900           300  0.333333      90.000000  1410.486
32            0.2      600           350  0.142857      51.428571  1158.879
33            0.2      700           350  0.142857      60.000000  1315.888
34            0.2      800           350  0.142857      68.571429  1253.347
35            0.2      900           350  0.142857      77.142857  1017.693
36            0.2      600           400  0.000000      45.000000  1076.224
37            0.2      700           400  0.000000      52.500000   973.377
38            0.2      800           400  0.000000      60.000000   963.636
39            0.2      900           400  0.000000      67.500000   830.909
40            0.4      500           200  1.000000      75.000000   770.093
41            0.4      600           200  1.000000      90.000000  1100.110
42            0.4      700           200  1.000000     105.000000  1357.092
43            0.4      800           200  1.000000     120.000000  1589.644
44            0.4      500           250  0.600000      60.000000  1209.259
45            0.4      600           250  0.600000      72.000000  1277.931
46            0.4      700           250  0.600000      84.000000  1364.815
47            0.4      800           250  0.600000      96.000000  1520.000
48            0.4      500           300  0.333333      50.000000  1090.741
49            0.4      600           300  0.333333      60.000000  1009.259
50            0.4      700           300  0.333333      70.000000  1046.957
51            0.4      800           300  0.333333      80.000000  1135.326
52            0.4      500           350  0.142857      42.857143   729.630
53            0.4      600           350  0.142857      51.428571   798.583
54            0.4      700           350  0.142857      60.000000   596.296
55            0.4      800           350  0.142857      68.571429   674.783
56            0.4      500           400  0.000000      37.500000   512.163
57            0.4      600           400  0.000000      45.000000   431.481
58            0.4      700           400  0.000000      52.500000   462.963
59            0.4      800           400  0.000000      60.000000   560.000
60            0.6      500           200  1.000000      75.000000   781.481
61            0.6      600           200  1.000000      90.000000  1168.730
62            0.6      700           200  1.000000     105.000000  1326.170
63            0.6      800           200  1.000000     120.000000  1519.064
64            0.6      500           250  0.600000      60.000000  1147.276
65            0.6      600           250  0.600000      72.000000  1327.778
66            0.6      700           250  0.600000      84.000000  1444.018
67            0.6      800           250  0.600000      96.000000  1398.240
68            0.6      500           300  0.333333      50.000000  1103.704
69            0.6      600           300  0.333333      60.000000  1185.185
70            0.6      700           300  0.333333      70.000000  1325.926
71            0.6      800           300  0.333333      80.000000  1301.984
72            0.6      500           350  0.142857      42.857143   987.037
73            0.6      600           350  0.142857      51.428571  1007.788
74            0.6      700           350  0.142857      60.000000  1083.525
75            0.6      800           350  0.142857      68.571429  1236.273
76            0.6      500           400  0.000000      37.500000   935.185
77            0.6      600           400  0.000000      45.000000   830.315
78            0.6      700           400  0.000000      52.500000   991.060
79            0.6      800           400  0.000000      60.000000   909.911
80            0.8      350           200  1.000000      52.500000   522.767
81            0.8      400           200  1.000000      60.000000   888.021
82            0.8      450           200  1.000000      67.500000  1149.533
83            0.8      500           200  1.000000      75.000000  1403.738
84            0.8      350           250  0.600000      42.000000   975.458
85            0.8      400           250  0.600000      48.000000  1102.804
86            0.8      450           250  0.600000      54.000000  1375.400
87            0.8      500           250  0.600000      60.000000  1314.399
88            0.8      350           300  0.333333      35.000000   956.395
89            0.8      400           300  0.333333      40.000000   898.648
90            0.8      450           300  0.333333      45.000000   842.991
91            0.8      500           300  0.333333      50.000000   925.234
92            0.8      350           350  0.142857      30.000000   521.495
93            0.8      400           350  0.142857      34.285714   547.664
94            0.8      450           350  0.142857      38.571429   535.301
95            0.8      500           350  0.142857      42.857143   517.593
96            0.8      350           400  0.000000      26.250000   429.630
97            0.8      400           400  0.000000      30.000000   448.148
98            0.8      450           400  0.000000      33.750000   427.778
99            0.8      500           400  0.000000      37.500000   439.815
100           1.0      350           200  1.000000      52.500000  1045.370
101           1.0      400           200  1.000000      60.000000  1435.514
102           1.0      450           200  1.000000      67.500000  1542.593
103           1.0      500           200  1.000000      75.000000  1531.532
104           1.0      350           250  0.600000      42.000000   625.926
105           1.0      400           250  0.600000      48.000000  1385.185
106           1.0      450           250  0.600000      54.000000  1466.667
107           1.0      500           250  0.600000      60.000000  1467.826
108           1.0      350           300  0.333333      35.000000  1157.407
109           1.0      400           300  0.333333      40.000000  1261.111
110           1.0      450           300  0.333333      45.000000  1287.037
111           1.0      500           300  0.333333      50.000000  1235.185
112           1.0      350           350  0.142857      30.000000  1042.593
113           1.0      400           350  0.142857      34.285714  1096.296
114           1.0      450           350  0.142857      38.571429  1074.074
115           1.0      500           350  0.142857      42.857143  1012.963
116           1.0      350           400  0.000000      26.250000   844.444
117           1.0      400           400  0.000000      30.000000   946.296
118           1.0      450           400  0.000000      33.750000   862.963
119           1.0      500           400  0.000000      37.500000   850.000

In [21]:
df_deposited_height.describe()

,NiTi粉末材料质量比例,激光功率（W）,移动速度（mm/min）,归一化线质量,激光能量密度（J/mm2）,沉积高度（μm）
count,120.000000,120.000000,120.00000,120.000000,120.000000,120.000000
mean,0.500000,608.333333,300.00000,0.415238,64.570238,1133.842025
std,0.342997,167.574558,71.00716,0.356285,24.505039,361.631371
min,0.000000,350.000000,200.00000,0.000000,26.250000,427.778000
25%,0.200000,487.500000,250.00000,0.142857,45.000000,921.403250
50%,0.500000,600.000000,300.00000,0.333333,60.000000,1103.704000
75%,0.800000,725.000000,350.00000,0.600000,77.857143,1377.846250
max,1.000000,900.000000,400.00000,1.000000,135.000000,1896.364000

In [22]:
X = df_deposited_height.iloc[:, :-1]
y = df_deposited_height.iloc[:, -1]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

regressor = TabPFNRegressor()  
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f'TabPFN模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN模型在测试集上的R²得分:', r2)

TabPFN模型在测试集上的均方根误差: 107.9830
TabPFN模型在测试集上的R²得分: 0.9294142200391884

In [24]:
reg = AutoTabPFNRegressor(max_time=300, device="cuda") 
reg.fit(X_train, y_train)

predictions = reg.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)

print(f'TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN_Post Hoc Ensembling模型在测试集上的R²得分:', r2)

INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Order of selections: [np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Val loss over iterations: [np.float64(4303.89680736023), np.float64(4282.398034231542), np.float64(4268.750621627684), np.float64(4268.750621627684), np.float64(4268.750621627684), np.float64(4268.750621627684), np.float64(4268.674279920884), np.float64(4268.674279920884), np.float64(4268.674279920884), np.float64(4268.518779544518), np.float64(4268.518779544518), np.float64(4268.518779544518), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207), np.float64(4268.498386876207)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Model losses: [ 4303.89680736  4448.22229392  4668.30314592  5998.14373447
  6381.31866434  6944.44826812  7825.88371687  8531.39144318
  9017.96465639  9197.91618693  9275.07110712  9687.51126969
  9770.15938016  9952.23754085 10128.13643188 10341.76668043
 10584.15792158 10620.34407822 10942.48522326 11039.75969128
 11119.21304261 12798.71740977 13466.30670709 13710.90075356
 14042.03726167]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Best weights: [0.69230769 0.30769231 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.        ]

TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: 103.8703
TabPFN_Post Hoc Ensembling模型在测试集上的R²得分: 0.9346884833439262

## Predict Left Wetting Angle

In [25]:
df_left = df.drop(df.columns[[0, 11]], axis=1)
df_left

,NiTi粉末材料质量比例,激光功率（W）,移动速度（mm/min）,归一化线质量,激光能量密度（J/mm2）,熔池宽度（μm）,熔池深度（μm）,沉积宽度（μm）,沉积高度（μm）,左润湿角（°）
0,0.0,600,200,1.000000,90.000000,2803.604,836.036,2075.6760,1762.162,131.315
1,0.0,700,200,1.000000,105.000000,3189.189,908.108,2428.8290,1751.351,109.671
2,0.0,800,200,1.000000,120.000000,3654.054,1001.802,2900.9010,1888.288,104.036
3,0.0,900,200,1.000000,135.000000,4075.676,1095.495,3189.1890,1780.180,92.068
4,0.0,600,250,0.600000,72.000000,2661.111,807.477,1824.0740,1659.259,138.094
5,0.0,700,250,0.600000,84.000000,3124.074,914.815,2301.8520,1648.148,132.679
6,0.0,800,250,0.600000,96.000000,3549.550,936.937,2724.3240,1517.117,99.851
7,0.0,900,250,0.600000,108.000000,3960.360,1045.045,3099.0990,1513.514,70.434
8,0.0,600,300,0.333333,60.000000,2631.776,798.131,2016.8220,1343.925,85.851
9,0.0,700,300,0.333333,70.000000,3018.692,829.907,2366.3550,1338.486,96.607
10,0.0,800,300,0.333333,80.000000,3440.741,888.889,2575.9260,1272.222,84.758
11,0.0,900,300,0.333333,90.000000,3830.631,1052.252,2980.1800,1269.069,84.346
12,0.0,600,350,0.142857,51.428571,2511.111,703.704,1892.5930,1101.852,103.191
13,0.0,700,350,0.142857,60.000000,2935.185,827.778,2261.1110,1103.704,84.693
14,0.0,800,350,0.142857,68.571429,3331.481,953.704,2711.1110,1107.407,68.371
15,0.0,900,350,0.142857,77.142857,3706.542,1044.860,2919.6260,1089.720,74.299
16,0.0,600,400,0.000000,45.000000,2476.636,748.598,1908.4110,968.224,90.815
17,0.0,700,400,0.000000,52.500000,2798.131,811.215,2128.9720,1061.682,90.000
18,0.0,800,400,0.000000,60.000000,3237.383,919.626,2582.2430,1001.869,71.130
19,0.0,900,400,0.000000,67.500000,3671.431,1031.776,2906.5421,1033.645,72.460
20,0.2,600,200,1.000000,90.000000,3299.065,1101.869,2633.6450,747.664,56.855
21,0.2,700,200,1.000000,105.000000,3585.047,1110.280,2885.9810,1323.173,59.699
22,0.2,800,200,1.000000,120.000000,3794.595,1149.550,3239.6400,1581.982,65.447
23,0.2,900,200,1.000000,135.000000,4198.198,1257.658,3434.2340,1732.710,66.110
24,0.2,600,250,0.600000,72.000000,2798.131,739.252,2480.3740,1641.121,72.713
25,0.2,700,250,0.600000,84.000000,3141.818,811.818,2745.4550,1813.333,69.777
26,0.2,800,250,0.600000,96.000000,3538.182,938.182,3189.0910,1896.364,65.406
27,0.2,900,250,0.600000,108.000000,3912.727,1087.273,3447.2730,1770.909,60.771
28,0.2,600,300,0.333333,60.000000,2594.595,624.324,2345.9460,1610.811,80.579
29,0.2,700,300,0.333333,70.000000,2980.180,762.162,2670.2700,1551.351,75.001
30,0.2,800,300,0.333333,80.000000,3357.387,967.863,2758.3200,1537.792,72.208
31,0.2,900,300,0.333333,90.000000,3775.846,1111.773,3301.8570,1410.486,54.641
32,0.2,600,350,0.142857,51.428571,2607.477,749.533,2254.2060,1158.879,70.253
33,0.2,700,350,0.142857,60.000000,2930.841,800.000,2540.1870,1315.888,71.441
34,0.2,800,350,0.142857,68.571429,3333.457,932.793,2905.9740,1253.347,57.060
35,0.2,900,350,0.142857,77.142857,3758.093,1105.285,3140.7350,1017.693,57.441
36,0.2,600,400,0.000000,45.000000,2520.951,666.397,2237.7170,1076.224,71.974
37,0.2,700,400,0.000000,52.500000,3025.090,832.849,2627.8940,973.377,57.356
38,0.2,800,400,0.000000,60.000000,3327.370,887.273,2869.1740,963.636,71.251
39,0.2,900,400,0.000000,67.500000,3778.182,1083.636,3290.9090,830.909,46.985
40,0.4,500,200,1.000000,75.000000,2869.813,947.664,2237.3830,770.093,62.137
41,0.4,600,200,1.000000,90.000000,3219.319,1038.363,2583.5670,1100.110,63.657
42,0.4,700,200,1.000000,105.000000,3519.845,1079.823,2976.8150,1357.092,76.677
43,0.4,800,200,1.000000,120.000000,3862.203,1166.712,3265.7970,1589.644,97.991
44,0.4,500,250,0.600000,60.000000,2529.630,701.852,2266.6670,1209.259,87.132
45,0.4,600,250,0.600000,72.000000,2867.533,828.190,2508.6370,1277.931,93.342
46,0.4,700,250,0.600000,84.000000,3237.037,929.630,2818.5190,1364.815,87.007
47,0.4,800,250,0.600000,96.000000,3565.326,970.435,3120.1570,1520.000,93.580
48,0.4,500,300,0.333333,50.000000,2407.692,622.222,2139.0940,1090.741,113.138
49,0.4,600,300,0.333333,60.000000,2824.113,798.148,2488.9720,1009.259,80.194
50,0.4,700,300,0.333333,70.000000,3175.669,873.043,2706.0870,1046.957,63.435
51,0.4,800,300,0.333333,80.000000,3532.533,1016.819,3021.1810,1135.326,69.847
52,0.4,500,350,0.142857,42.857143,2370.406,716.667,1974.1440,729.630,69.522
53,0.4,600,350,0.142857,51.428571,2809.224,840.860,2386.6640,798.583,67.561
54,0.4,700,350,0.142857,60.000000,3283.333,1033.333,2820.3700,596.296,33.075
55,0.4,800,350,0.142857,68.571429,3554.989,1126.978,2970.6380,674.783,37.003
56,0.4,500,400,0.000000,37.500000,2423.168,712.307,1993.0710,512.163,42.264
57,0.4,600,400,0.000000,45.000000,2883.333,905.556,2450.0000,431.481,34.259
58,0.4,700,400,0.000000,52.500000,3316.667,1031.481,2774.0740,462.963,38.870
59,0.4,800,400,0.000000,60.000000,3537.391,1172.174,2977.3910,560.000,29.964
60,0.6,500,200,1.000000,75.000000,2818.519,970.370,2190.7410,781.481,73.162
61,0.6,600,200,1.000000,90.000000,3200.335,997.728,2781.7800,1168.730,79.285
62,0.6,700,200,1.000000,105.000000,3481.501,1053.218,2948.0140,1326.170,101.088
63,0.6,800,200,1.000000,120.000000,3889.250,1121.005,3323.3840,1519.064,102.808
64,0.6,500,250,0.600000,60.000000,2533.388,692.285,2283.4330,1147.276,100.950
65,0.6,600,250,0.600000,72.000000,2872.222,805.556,2544.4440,1327.778,115.673
66,0.6,700,250,0.600000,84.000000,3242.262,885.189,2939.3170,1444.018,95.283
67,0.6,800,250,0.600000,96.000000,3621.709,1012.638,3200.0510,1398.240,86.991
68,0.6,500,300,0.333333,50.000000,2427.937,624.074,2176.1810,1103.704,97.996
69,0.6,600,300,0.333333,60.000000,2763.003,742.593,2481.5150,1185.185,88.355
70,0.6,700,300,0.333333,70.000000,3066.702,820.370,2751.8920,1325.926,78.950
71,0.6,800,300,0.333333,80.000000,3472.860,956.074,3118.8500,1301.984,85.550
72,0.6,500,350,0.142857,42.857143,2346.296,633.333,2122.2220,987.037,93.466
73,0.6,600,350,0.142857,51.428571,2677.110,726.117,2404.7340,1007.788,86.745
74,0.6,700,350,0.142857,60.000000,2982.070,818.298,2663.4680,1083.525,81.788
75,0.6,800,350,0.142857,68.571429,3258.208,874.197,2939.5630,1236.273,102.483
76,0.6,500,400,0.000000,37.500000,2227.778,585.185,2000.0000,935.185,74.453
77,0.6,600,400,0.000000,45.000000,2616.084,751.990,2325.5530,830.315,58.419
78,0.6,700,400,0.000000,52.500000,2911.196,807.118,2577.8580,991.060,74.313
79,0.6,800,400,0.000000,60.000000,3202.752,918.996,2817.5000,909.911,68.817
80,0.8,350,200,1.000000,52.500000,2161.314,778.913,1613.2020,522.767,77.931
81,0.8,400,200,1.000000,60.000000,2307.800,749.725,1922.4510,888.021,79.108
82,0.8,450,200,1.000000,67.500000,2553.296,756.389,2201.8980,1149.533,86.013
83,0.8,500,200,1.000000,75.000000,2706.565,755.140,2345.8310,1403.738,97.928
84,0.8,350,250,0.600000,42.000000,1951.577,517.811,1631.9570,975.458,108.878
85,0.8,400,250,0.600000,48.000000,2168.264,583.178,1895.0510,1102.804,96.571
86,0.8,450,250,0.600000,54.000000,2235.767,627.290,1836.0440,1375.400,129.324
87,0.8,500,250,0.600000,60.000000,2537.782,660.163,2247.8510,1314.399,96.365
88,0.8,350,300,0.333333,35.000000,1824.897,452.188,1527.9610,956.395,101.619
89,0.8,400,300,0.333333,40.000000,2094.112,554.219,1800.4700,898.648,86.814
90,0.8,450,300,0.333333,45.000000,2306.542,691.589,2001.8690,842.991,76.377
91,0.8,500,300,0.333333,50.000000,2493.515,743.925,2209.3960,925.234,69.639
92,0.8,350,350,0.142857,30.000000,1882.318,571.963,1557.0500,521.495,46.761
93,0.8,400,350,0.142857,34.285714,2069.280,642.991,1708.4480,547.664,56.237
94,0.8,450,350,0.142857,38.571429,2224.248,753.888,1755.7210,535.301,60.929
95,0.8,500,350,0.142857,42.857143,2474.074,835.185,1935.1850,517.593,56.273
96,0.8,350,400,0.000000,26.250000,1838.922,600.000,1454.6480,429.630,63.345
97,0.8,400,400,0.000000,30.000000,1996.296,657.407,1591.6670,448.148,49.479
98,0.8,450,400,0.000000,33.750000,2225.926,750.000,1792.5930,427.778,48.132
99,0.8,500,400,0.000000,37.500000,2333.439,818.519,1848.2230,439.815,45.426
100,1.0,350,200,1.000000,52.500000,2018.968,567.133,1674.4060,1045.370,111.101
101,1.0,400,200,1.000000,60.000000,2174.013,620.561,1796.3790,1435.514,110.786
102,1.0,450,200,1.000000,67.500000,2359.713,712.963,1970.7360,1542.593,133.576
103,1.0,500,200,1.000000,75.000000,2479.793,800.000,2158.8300,1531.532,133.196
104,1.0,350,250,0.600000,42.000000,1976.121,612.963,1620.5780,625.926,81.753
105,1.0,400,250,0.600000,48.000000,2000.104,553.704,1590.7800,1385.185,136.185
106,1.0,450,250,0.600000,54.000000,2224.074,650.000,1829.6300,1466.667,125.289
107,1.0,500,250,0.600000,60.000000,2334.079,747.826,1979.2800,1467.826,122.403
108,1.0,350,300,0.333333,35.000000,1757.525,433.333,1396.3560,1157.407,113.793
109,1.0,400,300,0.333333,40.000000,1946.296,474.074,1590.7410,1261.111,115.096
110,1.0,450,300,0.333333,45.000000,2026.200,607.407,1729.8530,1287.037,113.427
111,1.0,500,300,0.333333,50.000000,2227.951,698.148,1942.6240,1235.185,95.057
112,1.0,350,350,0.142857,30.000000,1711.737,424.074,1424.4220,1042.593,87.098
113,1.0,400,350,0.142857,34.285714,1866.667,505.556,1618.5190,1096.296,87.207
114,1.0,450,350,0.142857,38.571429,2050.030,618.519,1731.5300,1074.074,85.389
115,1.0,500,350,0.142857,42.857143,2253.704,692.593,1950.0000,1012.963,89.597
116,1.0,350,400,0.000000,26.250000,1672.222,418.519,1388.5800,844.444,89.102
117,1.0,400,400,0.000000,30.000000,1814.929,496.296,1531.5530,946.296,103.125
118,1.0,450,400,0.000000,33.750000,2014.815,551.852,1759.2590,862.963,84.129
119,1.0,500,400,0.000000,37.500000,2225.975,640.741,1968.5610,850.000,86.712

In [26]:
df_left.describe()

,NiTi粉末材料质量比例,激光功率（W）,移动速度（mm/min）,归一化线质量,激光能量密度（J/mm2）,熔池宽度（μm）,熔池深度（μm）,沉积宽度（μm）,沉积高度（μm）,左润湿角（°）
count,120.000000,120.000000,120.00000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,0.500000,608.333333,300.00000,0.415238,64.570238,2814.882050,812.593842,2361.604826,1133.842025,82.600308
std,0.342997,167.574558,71.00716,0.356285,24.505039,633.983643,191.163796,543.593936,361.631371,23.734517
min,0.000000,350.000000,200.00000,0.000000,26.250000,1672.222000,418.519000,1388.580000,427.778000,29.964000
25%,0.200000,487.500000,250.00000,0.142857,45.000000,2293.332500,664.838500,1918.941000,921.403250,68.168500
50%,0.500000,600.000000,300.00000,0.333333,60.000000,2800.867500,806.337000,2335.692000,1103.704000,82.958500
75%,0.800000,725.000000,350.00000,0.600000,77.857143,3319.342750,954.296500,2817.754750,1377.846250,96.937250
max,1.000000,900.000000,400.00000,1.000000,135.000000,4198.198000,1257.658000,3447.273000,1896.364000,138.094000

In [27]:
X = df_left.iloc[:, :-1]
y = df_left.iloc[:, -1]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

regressor = TabPFNRegressor()  
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f'TabPFN模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN模型在测试集上的R²得分:', r2)

TabPFN模型在测试集上的均方根误差: 9.5983
TabPFN模型在测试集上的R²得分: 0.7778543057813112

In [29]:
reg = AutoTabPFNRegressor(max_time=300, device="cuda") 
reg.fit(X_train, y_train)

predictions = reg.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)

print(f'TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN_Post Hoc Ensembling模型在测试集上的R²得分:', r2)

INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Order of selections: [np.int64(0), np.int64(1), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(2)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Val loss over iterations: [np.float64(76.24864911774179), np.float64(71.72972808511199), np.float64(71.72972808511199), np.float64(71.72972808511199), np.float64(71.5811181554637), np.float64(71.5811181554637), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55081857349064), np.float64(71.55041906289638), np.float64(71.55041906289638), np.float64(71.55041906289638), np.float64(71.55041906289638), np.float64(71.55041906289638), np.float64(71.54983502383922)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Model losses: [ 76.24864912  76.68303392  78.1171155   78.68103244  78.75900708
  79.1502365   80.06745712  80.89637771  80.9525102   82.58526228
  83.21193789  84.20019417  84.28731927  84.4795412   85.5938358
  89.51670871  90.36275389  91.91015047  91.9809801   95.63319188
  96.11636584  96.76456788  99.19151136 101.73721576 103.00799603]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Best weights: [0.4  0.44 0.16 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]

TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: 9.5435
TabPFN_Post Hoc Ensembling模型在测试集上的R²得分: 0.7803842474128695

## Predict Right Wetting Angle

In [30]:
df_right = df.drop(df.columns[[0, 10]], axis=1)
df_right

,NiTi粉末材料质量比例,激光功率（W）,移动速度（mm/min）,归一化线质量,激光能量密度（J/mm2）,熔池宽度（μm）,熔池深度（μm）,沉积宽度（μm）,沉积高度（μm）,右润湿角（°）
0,0.0,600,200,1.000000,90.000000,2803.604,836.036,2075.6760,1762.162,99.836
1,0.0,700,200,1.000000,105.000000,3189.189,908.108,2428.8290,1751.351,91.650
2,0.0,800,200,1.000000,120.000000,3654.054,1001.802,2900.9010,1888.288,87.592
3,0.0,900,200,1.000000,135.000000,4075.676,1095.495,3189.1890,1780.180,98.973
4,0.0,600,250,0.600000,72.000000,2661.111,807.477,1824.0740,1659.259,134.676
5,0.0,700,250,0.600000,84.000000,3124.074,914.815,2301.8520,1648.148,112.818
6,0.0,800,250,0.600000,96.000000,3549.550,936.937,2724.3240,1517.117,85.486
7,0.0,900,250,0.600000,108.000000,3960.360,1045.045,3099.0990,1513.514,87.241
8,0.0,600,300,0.333333,60.000000,2631.776,798.131,2016.8220,1343.925,128.480
9,0.0,700,300,0.333333,70.000000,3018.692,829.907,2366.3550,1338.486,81.174
10,0.0,800,300,0.333333,80.000000,3440.741,888.889,2575.9260,1272.222,74.827
11,0.0,900,300,0.333333,90.000000,3830.631,1052.252,2980.1800,1269.069,72.667
12,0.0,600,350,0.142857,51.428571,2511.111,703.704,1892.5930,1101.852,93.281
13,0.0,700,350,0.142857,60.000000,2935.185,827.778,2261.1110,1103.704,82.924
14,0.0,800,350,0.142857,68.571429,3331.481,953.704,2711.1110,1107.407,72.475
15,0.0,900,350,0.142857,77.142857,3706.542,1044.860,2919.6260,1089.720,60.186
16,0.0,600,400,0.000000,45.000000,2476.636,748.598,1908.4110,968.224,79.312
17,0.0,700,400,0.000000,52.500000,2798.131,811.215,2128.9720,1061.682,90.099
18,0.0,800,400,0.000000,60.000000,3237.383,919.626,2582.2430,1001.869,64.871
19,0.0,900,400,0.000000,67.500000,3671.431,1031.776,2906.5421,1033.645,56.901
20,0.2,600,200,1.000000,90.000000,3299.065,1101.869,2633.6450,747.664,37.387
21,0.2,700,200,1.000000,105.000000,3585.047,1110.280,2885.9810,1323.173,69.030
22,0.2,800,200,1.000000,120.000000,3794.595,1149.550,3239.6400,1581.982,78.397
23,0.2,900,200,1.000000,135.000000,4198.198,1257.658,3434.2340,1732.710,78.040
24,0.2,600,250,0.600000,72.000000,2798.131,739.252,2480.3740,1641.121,86.786
25,0.2,700,250,0.600000,84.000000,3141.818,811.818,2745.4550,1813.333,83.540
26,0.2,800,250,0.600000,96.000000,3538.182,938.182,3189.0910,1896.364,74.493
27,0.2,900,250,0.600000,108.000000,3912.727,1087.273,3447.2730,1770.909,67.094
28,0.2,600,300,0.333333,60.000000,2594.595,624.324,2345.9460,1610.811,79.472
29,0.2,700,300,0.333333,70.000000,2980.180,762.162,2670.2700,1551.351,70.521
30,0.2,800,300,0.333333,80.000000,3357.387,967.863,2758.3200,1537.792,79.327
31,0.2,900,300,0.333333,90.000000,3775.846,1111.773,3301.8570,1410.486,59.071
32,0.2,600,350,0.142857,51.428571,2607.477,749.533,2254.2060,1158.879,71.044
33,0.2,700,350,0.142857,60.000000,2930.841,800.000,2540.1870,1315.888,71.553
34,0.2,800,350,0.142857,68.571429,3333.457,932.793,2905.9740,1253.347,70.746
35,0.2,900,350,0.142857,77.142857,3758.093,1105.285,3140.7350,1017.693,54.520
36,0.2,600,400,0.000000,45.000000,2520.951,666.397,2237.7170,1076.224,89.059
37,0.2,700,400,0.000000,52.500000,3025.090,832.849,2627.8940,973.377,57.812
38,0.2,800,400,0.000000,60.000000,3327.370,887.273,2869.1740,963.636,60.386
39,0.2,900,400,0.000000,67.500000,3778.182,1083.636,3290.9090,830.909,48.168
40,0.4,500,200,1.000000,75.000000,2869.813,947.664,2237.3830,770.093,56.718
41,0.4,600,200,1.000000,90.000000,3219.319,1038.363,2583.5670,1100.110,77.291
42,0.4,700,200,1.000000,105.000000,3519.845,1079.823,2976.8150,1357.092,69.834
43,0.4,800,200,1.000000,120.000000,3862.203,1166.712,3265.7970,1589.644,80.240
44,0.4,500,250,0.600000,60.000000,2529.630,701.852,2266.6670,1209.259,83.555
45,0.4,600,250,0.600000,72.000000,2867.533,828.190,2508.6370,1277.931,77.739
46,0.4,700,250,0.600000,84.000000,3237.037,929.630,2818.5190,1364.815,76.987
47,0.4,800,250,0.600000,96.000000,3565.326,970.435,3120.1570,1520.000,87.717
48,0.4,500,300,0.333333,50.000000,2407.692,622.222,2139.0940,1090.741,78.918
49,0.4,600,300,0.333333,60.000000,2824.113,798.148,2488.9720,1009.259,62.838
50,0.4,700,300,0.333333,70.000000,3175.669,873.043,2706.0870,1046.957,58.400
51,0.4,800,300,0.333333,80.000000,3532.533,1016.819,3021.1810,1135.326,63.155
52,0.4,500,350,0.142857,42.857143,2370.406,716.667,1974.1440,729.630,58.807
53,0.4,600,350,0.142857,51.428571,2809.224,840.860,2386.6640,798.583,51.916
54,0.4,700,350,0.142857,60.000000,3283.333,1033.333,2820.3700,596.296,34.321
55,0.4,800,350,0.142857,68.571429,3554.989,1126.978,2970.6380,674.783,40.605
56,0.4,500,400,0.000000,37.500000,2423.168,712.307,1993.0710,512.163,44.042
57,0.4,600,400,0.000000,45.000000,2883.333,905.556,2450.0000,431.481,30.038
58,0.4,700,400,0.000000,52.500000,3316.667,1031.481,2774.0740,462.963,29.943
59,0.4,800,400,0.000000,60.000000,3537.391,1172.174,2977.3910,560.000,30.522
60,0.6,500,200,1.000000,75.000000,2818.519,970.370,2190.7410,781.481,63.623
61,0.6,600,200,1.000000,90.000000,3200.335,997.728,2781.7800,1168.730,69.295
62,0.6,700,200,1.000000,105.000000,3481.501,1053.218,2948.0140,1326.170,80.901
63,0.6,800,200,1.000000,120.000000,3889.250,1121.005,3323.3840,1519.064,84.275
64,0.6,500,250,0.600000,60.000000,2533.388,692.285,2283.4330,1147.276,72.730
65,0.6,600,250,0.600000,72.000000,2872.222,805.556,2544.4440,1327.778,77.241
66,0.6,700,250,0.600000,84.000000,3242.262,885.189,2939.3170,1444.018,84.548
67,0.6,800,250,0.600000,96.000000,3621.709,1012.638,3200.0510,1398.240,64.629
68,0.6,500,300,0.333333,50.000000,2427.937,624.074,2176.1810,1103.704,90.611
69,0.6,600,300,0.333333,60.000000,2763.003,742.593,2481.5150,1185.185,72.063
70,0.6,700,300,0.333333,70.000000,3066.702,820.370,2751.8920,1325.926,69.459
71,0.6,800,300,0.333333,80.000000,3472.860,956.074,3118.8500,1301.984,54.084
72,0.6,500,350,0.142857,42.857143,2346.296,633.333,2122.2220,987.037,66.991
73,0.6,600,350,0.142857,51.428571,2677.110,726.117,2404.7340,1007.788,59.621
74,0.6,700,350,0.142857,60.000000,2982.070,818.298,2663.4680,1083.525,59.685
75,0.6,800,350,0.142857,68.571429,3258.208,874.197,2939.5630,1236.273,66.088
76,0.6,500,400,0.000000,37.500000,2227.778,585.185,2000.0000,935.185,75.292
77,0.6,600,400,0.000000,45.000000,2616.084,751.990,2325.5530,830.315,46.989
78,0.6,700,400,0.000000,52.500000,2911.196,807.118,2577.8580,991.060,63.646
79,0.6,800,400,0.000000,60.000000,3202.752,918.996,2817.5000,909.911,66.613
80,0.8,350,200,1.000000,52.500000,2161.314,778.913,1613.2020,522.767,51.297
81,0.8,400,200,1.000000,60.000000,2307.800,749.725,1922.4510,888.021,60.313
82,0.8,450,200,1.000000,67.500000,2553.296,756.389,2201.8980,1149.533,82.266
83,0.8,500,200,1.000000,75.000000,2706.565,755.140,2345.8310,1403.738,84.451
84,0.8,350,250,0.600000,42.000000,1951.577,517.811,1631.9570,975.458,87.060
85,0.8,400,250,0.600000,48.000000,2168.264,583.178,1895.0510,1102.804,83.447
86,0.8,450,250,0.600000,54.000000,2235.767,627.290,1836.0440,1375.400,101.351
87,0.8,500,250,0.600000,60.000000,2537.782,660.163,2247.8510,1314.399,91.783
88,0.8,350,300,0.333333,35.000000,1824.897,452.188,1527.9610,956.395,94.772
89,0.8,400,300,0.333333,40.000000,2094.112,554.219,1800.4700,898.648,75.272
90,0.8,450,300,0.333333,45.000000,2306.542,691.589,2001.8690,842.991,57.911
91,0.8,500,300,0.333333,50.000000,2493.515,743.925,2209.3960,925.234,68.658
92,0.8,350,350,0.142857,30.000000,1882.318,571.963,1557.0500,521.495,57.728
93,0.8,400,350,0.142857,34.285714,2069.280,642.991,1708.4480,547.664,53.922
94,0.8,450,350,0.142857,38.571429,2224.248,753.888,1755.7210,535.301,39.997
95,0.8,500,350,0.142857,42.857143,2474.074,835.185,1935.1850,517.593,43.112
96,0.8,350,400,0.000000,26.250000,1838.922,600.000,1454.6480,429.630,45.841
97,0.8,400,400,0.000000,30.000000,1996.296,657.407,1591.6670,448.148,46.948
98,0.8,450,400,0.000000,33.750000,2225.926,750.000,1792.5930,427.778,35.710
99,0.8,500,400,0.000000,37.500000,2333.439,818.519,1848.2230,439.815,38.117
100,1.0,350,200,1.000000,52.500000,2018.968,567.133,1674.4060,1045.370,80.196
101,1.0,400,200,1.000000,60.000000,2174.013,620.561,1796.3790,1435.514,106.051
102,1.0,450,200,1.000000,67.500000,2359.713,712.963,1970.7360,1542.593,99.908
103,1.0,500,200,1.000000,75.000000,2479.793,800.000,2158.8300,1531.532,106.527
104,1.0,350,250,0.600000,42.000000,1976.121,612.963,1620.5780,625.926,74.126
105,1.0,400,250,0.600000,48.000000,2000.104,553.704,1590.7800,1385.185,105.394
106,1.0,450,250,0.600000,54.000000,2224.074,650.000,1829.6300,1466.667,92.851
107,1.0,500,250,0.600000,60.000000,2334.079,747.826,1979.2800,1467.826,112.249
108,1.0,350,300,0.333333,35.000000,1757.525,433.333,1396.3560,1157.407,92.904
109,1.0,400,300,0.333333,40.000000,1946.296,474.074,1590.7410,1261.111,104.948
110,1.0,450,300,0.333333,45.000000,2026.200,607.407,1729.8530,1287.037,104.390
111,1.0,500,300,0.333333,50.000000,2227.951,698.148,1942.6240,1235.185,104.985
112,1.0,350,350,0.142857,30.000000,1711.737,424.074,1424.4220,1042.593,115.757
113,1.0,400,350,0.142857,34.285714,1866.667,505.556,1618.5190,1096.296,81.876
114,1.0,450,350,0.142857,38.571429,2050.030,618.519,1731.5300,1074.074,85.985
115,1.0,500,350,0.142857,42.857143,2253.704,692.593,1950.0000,1012.963,75.340
116,1.0,350,400,0.000000,26.250000,1672.222,418.519,1388.5800,844.444,82.042
117,1.0,400,400,0.000000,30.000000,1814.929,496.296,1531.5530,946.296,77.249
118,1.0,450,400,0.000000,33.750000,2014.815,551.852,1759.2590,862.963,75.736
119,1.0,500,400,0.000000,37.500000,2225.975,640.741,1968.5610,850.000,67.957

In [31]:
df_right.describe()

,NiTi粉末材料质量比例,激光功率（W）,移动速度（mm/min）,归一化线质量,激光能量密度（J/mm2）,熔池宽度（μm）,熔池深度（μm）,沉积宽度（μm）,沉积高度（μm）,右润湿角（°）
count,120.000000,120.000000,120.00000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,0.500000,608.333333,300.00000,0.415238,64.570238,2814.882050,812.593842,2361.604826,1133.842025,73.919267
std,0.342997,167.574558,71.00716,0.356285,24.505039,633.983643,191.163796,543.593936,361.631371,20.509268
min,0.000000,350.000000,200.00000,0.000000,26.250000,1672.222000,418.519000,1388.580000,427.778000,29.943000
25%,0.200000,487.500000,250.00000,0.142857,45.000000,2293.332500,664.838500,1918.941000,921.403250,60.060750
50%,0.500000,600.000000,300.00000,0.333333,60.000000,2800.867500,806.337000,2335.692000,1103.704000,75.049500
75%,0.800000,725.000000,350.00000,0.600000,77.857143,3319.342750,954.296500,2817.754750,1377.846250,85.610750
max,1.000000,900.000000,400.00000,1.000000,135.000000,4198.198000,1257.658000,3447.273000,1896.364000,134.676000

In [32]:
X = df_right.iloc[:, :-1]
y = df_right.iloc[:, -1]

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

regressor = TabPFNRegressor()  
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f'TabPFN模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN模型在测试集上的R²得分:', r2)

TabPFN模型在测试集上的均方根误差: 7.4306
TabPFN模型在测试集上的R²得分: 0.8215659069220371

In [34]:
reg = AutoTabPFNRegressor(max_time=300, device="cuda") 
reg.fit(X_train, y_train)

predictions = reg.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)

print(f'TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: {rmse:.4f}')
print('TabPFN_Post Hoc Ensembling模型在测试集上的R²得分:', r2)

INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Order of selections: [np.int64(0), np.int64(1), np.int64(4), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(4), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(4), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(4), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(1)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Val loss over iterations: [np.float64(67.44759609805234), np.float64(66.29054188438548), np.float64(66.2750706754481), np.float64(66.19072227706255), np.float64(66.12909759414549), np.float64(66.12909759414549), np.float64(66.12864446333313), np.float64(66.12864446333313), np.float64(66.12864446333313), np.float64(66.12864446333313), np.float64(66.12864446333313), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595), np.float64(66.12430464983595)]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Model losses: [67.4475961  68.26104437 69.68710314 69.89988611 70.04816738 70.23125487
 70.52472823 70.69443382 71.60254184 72.53133986 72.89906156 73.37044179
 73.92969623 73.99872663 74.17662228 74.30286738 74.3823418  74.86352736
 75.24074282 76.56760754 77.39028469 77.41094813 78.87961739 84.90105533
 87.20172879]
INFO:tabpfn_extensions.post_hoc_ensembles.greedy_weighted_ensemble:Best weights: [0.41666667 0.41666667 0.         0.         0.16666667 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.        ]

TabPFN_Post Hoc Ensembling模型在测试集上的均方根误差: 7.2693
TabPFN_Post Hoc Ensembling模型在测试集上的R²得分: 0.8292291324023033